name: "Cloudfix-Linter"

on:
  pull_request:

jobs:
  terraform:
    name: "Cloudfix-Linter"
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          # terraform_version: 0.13.0:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        id: init
        run: terraform init
      
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
      
      - name: Terraform Show
        if: github.event_name == 'pull_request'
        run: terraform show -json | head -2 | tail -1 > tf.show

      - name: Generate Mock reccomendations
        if: github.event_name == 'pull_request'
        run: python gen_recco.py tf.show

      - name: Installing tflint and cloudfix-linter
        if: github.event_name == 'pull_request'
        run: bash installScript.sh

      - name: Cloudfix-Linter Init
        id: linterinit
        if: github.event_name == 'pull_request'
        run: ./cloudfix-linter/cloudfix-linter init
      
      - name: Comment Reccomendation
        id: prcomment
        if: github.event_name == 'pull_request'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: export pr_number=${{ github.event.pull_request.number }}; export repository=${{ github.repository }}; sh script.sh
